### ISSUE TITLE
Import with JDK11 fails due to missing javax.activation

### ISSUE THREAD

**Issue by climategadgets** [fsanaulla/chronicler#183]
How to reproduce:

Import a project on IntelliJ with JDK11 installed on the box.
Expected behavior: project imports.
Actual behavior: import fails, exception trace below.
Root cause: `javax.activation` is missing from JDK11.
Possible fix:
```
diff --git a/project/plugins.sbt b/project/plugins.sbt
index 237c09f7..0ffb9fba 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,3 +1,5 @@
+libraryDependencies += "com.sun.activation" % "javax.activation" % "1.2.0"
+
 resolvers += "Era7 maven releases" at "https://s3-eu-west-1.amazonaws.com/releases.era7.com"

 addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
```

Exception trace:
```
...
[info] Resolving key references (15451 settings) ...
[error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[error]     at ohnosequences.sbt.GithubRelease$defs$.ghreleaseMediaTypesMap(GithubRelease.scala:45)
[error]     at ohnosequences.sbt.SbtGithubReleasePlugin$.$anonfun$projectSettings$14(SbtGithubReleasePlugin.scala:29)
[error]     at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[error]     at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:204)
[error]     at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error]     at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error]     at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]     at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error]     at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]     at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
[error]     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]     at ohnosequences.sbt.GithubRelease$defs$.ghreleaseMediaTypesMap(GithubRelease.scala:45)
[error]     at ohnosequences.sbt.SbtGithubReleasePlugin$.$anonfun$projectSettings$14(SbtGithubReleasePlugin.scala:29)
[error]     at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[error]     at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:204)
[error]     at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error]     at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error]     at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]     at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error]     at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]     at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[error] Use 'last' for the full log.
Invalid response.```

**Comment by fsanaulla** [comment]
Hello, @climategadgets.

Please take a look at it: https://github.com/fsanaulla/chronicler-spark/issues/17.

Let me know if the issue still occurs.
